development:
  DB_USERNAME: postgres
  DB_PASSWORD: test123
  DB_IP: localhost
  DB_NAME: ttps_2017
test:
  DB_USERNAME: postgres
  DB_PASSWORD: test123
  DB_IP: localhost
  DB_NAME: ttps_2017
production:
  DB_USERNAME: 
  DB_PASSWORD: 
  DB_IP: 
  DB_NAME: 

